### ISSUE TITLE
Feature Request: MariaDB/MongoDB support

### ISSUE THREAD

**Issue by jonesdevelopment** [jonesdevelopment/sonar#141]
Implement support for more than one database type:
- [x] MySQL
- [x] MariaDB

**Comment by micartey** [comment]
Please assign a branch or pull request for others to work on this as well.

You can find it on the right side of this issue under **Development**

**Comment by jonesdevelopment** [comment]
MongoDB is not possible to implement as ORMLite doesn't support it; and no one uses PostgreSQL, let's be honest.
I implemented (experimental) support for MariaDB though.
