### ISSUE TITLE
InGame Notifications and information about attack.

### ISSUE THREAD

**Issue by adabugra** [jonesdevelopment/sonar#155]
### Information

![image](https://github.com/jonesdevelopment/sonar/assets/57899270/de9399c6-457f-4ff5-9c56-b3c3c9941a10)
Like this, and maybe ingame titles that informs mods about an attack started.

### Reason

It can inform the mods about the attack.

**Comment by jonesdevelopment** [comment]
Not a bad idea in general, but I don't want Sonar 2.0 to end up like 1.0; Sonar 1.0 is mainly used by people to test their connections or IP addresses per second to advertise their illegal botting or (D)DoSing tools. I don't like that.
I do not think a "peak connections per second" or a "peak IP addresses per second" feature are worth implementing.

You can use the Discord webhook implementation for attack notifications, and I believe it may be a nice idea to implement chat notifications once an attack has been detected. What do you think?

**Comment by jonesdevelopment** [comment]
> and information about attack.

Information about past attacks is a feature that is reserved for the web panel and won't come to 2.0 while the web panel is not out.
https://github.com/users/jonesdevelopment/projects/3?pane=issue&itemId=48685538

**Comment by jonesdevelopment** [comment]
@adabugra I won't add "peak connections per second" nor "peak IP addresses per second", but I'm down to implement title chat and notifications (when an attack starts/is detected) for moderators using different permissions (sonar.notify?)

**Comment by jonesdevelopment** [comment]
![image](https://github.com/jonesdevelopment/sonar/assets/73846784/5a851382-4bcd-4f6a-bc39-0233074789f2)
Working on it... ("Title" and "Subtitle" are placeholders)
