### ISSUE TITLE
Bug Report: LibreLogin incompatiblity on BungeeCord

### ISSUE THREAD

**Issue by overkidding** [jonesdevelopment/sonar#163]
### General information

LibreLogin plugin not supported due to custom InitialHandler

### Steps to reproduce

1. LibreLogin
2. Sonar
3. Join

### Sonar dump

[Sonar]: Generated dump: {"memory":{"total":"4.0 GB","max":"4.0 GB","free":"3.8 GB","used":"230.9 MB"},"runtime":{"virtualCores":12,"jvmArguments":["-Xmx4G","-Xms4G"],"vmName":"OpenJDK 64-Bit Server VM","vmVendor":"Debian","vmVersion":"17.0.7+7-Debian-1deb11u1"},"os":{"name":"Linux","arch":"amd64","version":"5.10.0-26-amd64"},"sonar":{"version":"2.0.15-bea1d29-1006-main","platform":"BUNGEE","isOnMainBranch":true}}

### Additional information

https://pastebin.com/hA4xMHiB

**Comment by jonesdevelopment** [comment]
Seems to be similar to https://github.com/jonesdevelopment/sonar-legacy/pull/8
Thanks for reporting this. I'll implement a fix ASAP.

**Comment by overkidding** [comment]
> Seems to be similar to https://github.com/jonesdevelopment/sonar-legacy/pull/8
> Thanks for reporting this. I'll implement a fix ASAP.

Thanks
