### ISSUE TITLE
Feature Request: Support MongoDB as a database type

### ISSUE THREAD

**Issue by overkidding** [jonesdevelopment/sonar#170]
### Information

I think that adding MongoDB as a supported database too could be a good idea.

### Reason

Not everyone uses MySQL as their primary db and some don't even have it installed (like me) to save verified players i think it would be good to add it

**Comment by jonesdevelopment** [comment]
Duplicate of https://github.com/jonesdevelopment/sonar/issues/141 — I added MongoDB as an additional database type.
