### ISSUE TITLE
Bug Report: [incompatibility] Protocolize on BungeeCord

### ISSUE THREAD

**Issue by overkidding** [jonesdevelopment/sonar#171]
### General information

> [10:13:09 ERROR]: Exception occurred while injecting into netty pipeline
> java.util.NoSuchElementException: protocolize2-decoder
>         at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[proxy.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
>         at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:302) ~[proxy.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
>         at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:290) ~[proxy.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
>         at dev.simplix.protocolize.bungee.netty.NettyPipelineInjector.injectAfter(NettyPipelineInjector.java:36) ~[?:?]
>         at dev.simplix.protocolize.bungee.listener.PlayerListener.onPing(PlayerListener.java:34) ~[?:?]
>         at jdk.internal.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[?:?]
>         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>         at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
>         at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[proxy.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
>         at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[proxy.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
>         at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:511) ~[proxy.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
>         at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:350) ~[proxy.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
>         at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:300) ~[proxy.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
>         at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:410) ~[proxy.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
>         at xyz.jonesdev.sonar.bungee.fallback.FallbackInitialHandler.lambda$handle$0(FallbackInitialHandler.java:133) ~[?:?]
>         at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
>         at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
>         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
>         at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
>         at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
>         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
>         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

### Steps to reproduce

1. Protocolize
2. Protocolize Legacy Data
3. Sonar (built from source code)
4. Send a bot attack

### Sonar dump

[Sonar]: Generated dump: {"memory":{"total":"4.0 GB","max":"4.0 GB","free":"2.5 GB","used":"1.5 GB"},"runtime":{"virtualCores":12,"jvmArguments":["-Xmx4G","-Xms4G"],"vmName":"OpenJDK 64-Bit Server VM","vmVendor":"Debian","vmVersion":"17.0.7+7-Debian-1deb11u1"},"os":{"name":"Linux","arch":"amd64","version":"5.10.0-26-amd64"},"sonar":{"version":"2.0.15-512faa9-1015-main","platform":"BUNGEE","isOnMainBranch":true}}

**Comment by FallenCrystal** [comment]
does this happen to you every time you ping? if not, it could be an issue with async ping processing.

**Comment by overkidding** [comment]
> does this happen to you every time you ping? if not, it could be an issue with async ping processing.

With normal pings (from players) it does not happen, with bot ping attacks it starts to spam
![image](https://github.com/jonesdevelopment/sonar/assets/46853321/4a42e4fa-c254-43eb-83e3-2f9003b9d1da)

**Comment by jonesdevelopment** [comment]
Could this potentially be a problem with the current InitialHandler implementation?

**Comment by overkidding** [comment]
> Could this potentially be a problem with the current InitialHandler implementation?

could be, i don't really know i only know that protocolize injects their decoder at the ping event ([PlayerListener](https://github.com/Exceptionflug/protocolize/blob/master/protocolize-bungeecord/src/main/java/dev/simplix/protocolize/bungee/listener/PlayerListener.java)) so if sonar rejects/overwrites the injection it will throw the error

**Comment by jonesdevelopment** [comment]
> could be, i don't really know i only know that protocolize injects their decoder at the ping event ([PlayerListener]

It could also be that I have to run the rest of the ping handling in the channel's even loop, or since I'm using `CompletableFuture` it creates too many threads and, therefore, throws an error.

**Comment by overkidding** [comment]
> > could be, i don't really know i only know that protocolize injects their decoder at the ping event ([PlayerListener]
> 
> It could also be that I have to run the rest of the ping handling in the channel's even loop, or since I'm using `CompletableFuture` it creates too many threads and, therefore, throws an error.

yea could also be that

**Comment by jonesdevelopment** [comment]
I will likely remove the asynchronous ping handling to avoid these compatibility problems. It's a nice feature and blocks some attacks, but I cannot leave it in a production version if it causes issues with other plugins.

**Comment by jonesdevelopment** [comment]
This will likely be fixed whenever https://github.com/jonesdevelopment/sonar/pull/174 is merged.

**Comment by overkidding** [comment]
Protocolize developer replied: https://github.com/Exceptionflug/protocolize/issues/225#issuecomment-1906289554

**Comment by jonesdevelopment** [comment]
@FallenCrystal Can we close this? (Fixed in https://github.com/jonesdevelopment/sonar/pull/174)
