### ISSUE TITLE
Bug Report: Geyser players are unable to connect

### ISSUE THREAD

**Issue by jonesdevelopment** [jonesdevelopment/sonar#172]
### General information

People have been reporting issues with Geyser (floodgate).
I've tested Geyser before, but only on Velocity and it seemed to work "just fine".

### Steps to reproduce

1. Join the proxy with a bedrock client

### Sonar dump

/

### Additional information

I need to collect more information on this issue. More information and related classes:
- https://github.com/GeyserMC/Floodgate
- https://github.com/jonesdevelopment/sonar/blob/main/sonar-common/src/main/java/xyz/jonesdev/sonar/common/utility/geyser/GeyserUtil.java

**Comment by FallenCrystal** [comment]
Failed on BungeeCord:
```
[Geyser-BungeeCord]: Cannot reply to ClientboundHelloPacket without profile and access token.
```
sonar seems to have succeeded exempting geyser. but due to certain factors. client can't join. (test with #174)

**Comment by jonesdevelopment** [comment]
@FallenCrystal BungeeCord is having some issues at the moment. We need to try to figure out what's causing the issues in https://github.com/jonesdevelopment/sonar/pull/174 before we can investigate this.

**Comment by FallenCrystal** [comment]
> @FallenCrystal BungeeCord is having some issues at the moment. We need to try to figure out what's causing the issues in #174 before we can investigate this.

It doesn't actually have anything to do with #174. installing sonar will have the problem (i mean: https://github.com/jonesdevelopment/sonar/issues/172#issuecomment-1906476644). even if it doesn't replace the HandlerBoss

**Comment by FallenCrystal** [comment]
![image](https://github.com/jonesdevelopment/sonar/assets/71176602/bc301141-b795-41ef-b922-d85d6e976e92)

@jonesdevelopment  (for geyser on bungeecord) have u ever thought about using original channel initializer?
this is probably the easiest solution i know of at the moment.
but if you want to figure out why exactly it doesn't work. this may not be applicable.

> https://github.com/FallenCrystal/Sonar/tree/original-initializer-for-geyser

**Comment by jonesdevelopment** [comment]
What does `BaseInjectionHelper#handleOriginal(channel)` do?

**Comment by jonesdevelopment** [comment]
> btw i post it here because im blocked by discord auto-mod

You cannot @ me because I was getting annoyed by a lot of people spam pinging me.

**Comment by jonesdevelopment** [comment]
@FallenCrystal I don't have Bedrock so I cannot test Geyser/floodgate. Can you please test if Bedrock works on Velocity?

**Comment by jonesdevelopment** [comment]
> have u ever thought about using original channel initializer

What about TCPShield? If the player joins through a reverse proxy, their port won't be 0 and we'd have to use a different method of checking for Geyser...

**Comment by FallenCrystal** [comment]
> > have u ever thought about using original channel initializer
> 
> What about TCPShield? If the player joins through a reverse proxy, their port won't be 0 and we'd have to use a different method of checking for Geyser...

i haven't tried tcpshield. u mean at least handle `HAProxyMessage` or other thing?

**Comment by jonesdevelopment** [comment]
> i haven't tried tcpshield. u mean at least handle `HAProxyMessage` or other thing?

Yeah, if the connection goes though TCPShield is must have a different IP and port at first, right?

**Comment by micartey** [comment]
> @FallenCrystal I don't have Bedrock so I cannot test Geyser/floodgate. Can you please test if Bedrock works on Velocity?

Tested it on Spigot (I know that this is not a proxy) but it works perfectly there.
Therefore, I believe this is either vendor-specific or a proxy thing (although the first thing is more likely)

@jonesdevelopment we can test it on your velocity installation if you like.

**Comment by jonesdevelopment** [comment]
> Tested it on Spigot (I know that this is not a proxy) but it works perfectly there.

Sonar doesn't support bukkit yet.

**Comment by jonesdevelopment** [comment]
> @jonesdevelopment we can test it on your velocity installation if you like.

That would be a huge help! I'll let you know when I'm available.

**Comment by micartey** [comment]
> Sonar doesn't support bukkit yet.

Wdym? It loads 😂 
Is there just no functionality yet?

**Comment by FallenCrystal** [comment]
> Therefore, I believe this is either vendor-specific or a proxy thing (although the first thing is more likely)

https://discord.com/channels/923308209769426994/1116406180332445746/1200155903542968350

> Wdym? It loads 😂
> Is there just no functionality yet?

as far as i know. sonar on bukkit does not implement any antibot modules. (ATM)

**Comment by jonesdevelopment** [comment]
> Is there just no functionality yet?

Yeah. All shared modules are loading but there's no anti-bot component yet because of NMS and the injection bs...

**Comment by micartey** [comment]
We should move this to another thread/issue and discuss this further.
There surely are better ways to do that 

#179

**Comment by jonesdevelopment** [comment]
2.0.16 seems to fix some issues regarding Geyser... probably because of the new plugin loading structure implemented in #182?

**Comment by jonesdevelopment** [comment]
The Geyser standalone proxy seems to have some issues (https://discord.com/channels/923308209769426994/1116406180332445746/1201691926965788772)

**Comment by belzzebuh** [comment]
i have the same problem with latest version on Sonar, i'm using Geyser Standalone but all geyser players have this error: 
![Screenshot_2024-02-04-09-55-52-26](https://github.com/jonesdevelopment/sonar/assets/90662594/cb0130c2-ee78-4efd-81e4-7837c68edccd)

is it possible to add a geyser ignore to sonar? this would help to directly remove the possibility of geyser users going through the antibot.

**Comment by jonesdevelopment** [comment]
> is it possible to add a geyser ignore to sonar? this would help to directly remove the possibility of geyser users going through the antibot.

That's what it's supposed to do. The problem lies in detecting Geyser standalone players. I don't have much time at the moment, so I cannot really look into it that much.
I've done some research, but I don't have an ETA yet, but I'm sure I'll figure this out in a bit.

**Comment by jonesdevelopment** [comment]
[This commit](<https://github.com/jonesdevelopment/sonar/commit/468a11e0be6d19a3640399cfaf665b0a61261b07#diff-199a9da3c575d6086d108136a73e2a59324ec527a20136bcce82ed0f04ce6e37L45>) may be helpful in solving this problem.
