### ISSUE TITLE
Bug Report: Pings/connections are blocked

### ISSUE THREAD

**Issue by overkidding** [jonesdevelopment/sonar#173]
### General information

Ping and connections are blocked by default with some users i'm getting lots of reports

### Steps to reproduce

I really don't know, they are unable to ping the server while Sonar is in the plugins folder.

### Sonar dump

[Sonar]: Generated dump: {"memory":{"total":"4.0 GB","max":"4.0 GB","free":"2.7 GB","used":"1.3 GB"},"runtime":{"virtualCores":12,"jvmArguments":["-Xmx4G","-Xms4G"],"vmName":"OpenJDK 64-Bit Server VM","vmVendor":"Debian","vmVersion":"17.0.7+7-Debian-1deb11u1"},"os":{"name":"Linux","arch":"amd64","version":"5.10.0-26-amd64"},"sonar":{"version":"2.0.15-512faa9-1015-main","platform":"BUNGEE","isOnMainBranch":true}}

**Comment by jonesdevelopment** [comment]
Related to #169 and #171, will be fixed ASAP — The BungeeCord packet handling will be recoded.

**Comment by overkidding** [comment]
Fix ASAP i'm running Sonar on my production server and lots of players are having this issues

**Comment by jonesdevelopment** [comment]
> Fix ASAP i'm running Sonar on my production server and lots of players are having this issues

Are logins affected by this in any way?

**Comment by overkidding** [comment]
> > Fix ASAP i'm running Sonar on my production server and lots of players are having this issues
> 
> Are logins affected by this in any way?

Yes they are

**Comment by overkidding** [comment]
![image](https://github.com/jonesdevelopment/sonar/assets/46853321/7a70edd9-ec07-46ed-a98c-365e8c232a5d)

**Comment by jonesdevelopment** [comment]
Are you running ViaVersion on the proxy?

**Comment by overkidding** [comment]
> Are you running ViaVersion on the proxy?

No

**Comment by jonesdevelopment** [comment]
> No

Can you upload your logs on https://mclo.gs and provide me a list of the plugins you're using?

**Comment by overkidding** [comment]
> > No
> 
> Can you upload your logs on https://mclo.gs and provide me a list of the plugins you're using?

On the log there are player ips but there are no exceptions if you're searching for them

**Comment by jonesdevelopment** [comment]
> On the log there are player ips [...]

The website automatically censors them, I just wanted to see if there are any special cases happening (e.g. Geyser, Protocolize, etc.)

**Comment by overkidding** [comment]
![image](https://github.com/jonesdevelopment/sonar/assets/46853321/11a1fdc5-4276-4210-9ef8-4e3d1f8edd0d)
PixelMOTD is the only thing that interefeers with the ping of the server due to MOTD modifications v4Guard lets the player join everytime, proxy is a queue plugin that is used as a bridge only so i don't think anything is related to ping/connections

**Comment by overkidding** [comment]
https://github.com/jonesdevelopment/sonar/issues/173#issuecomment-1906321606

**Comment by overkidding** [comment]
https://mclo.gs/CZO2Weg

**Comment by jonesdevelopment** [comment]
Could you try using default BungeeCord just for now? https://ci.md-5.net/job/BungeeCord/

**Comment by overkidding** [comment]
> Could you try using default BungeeCord just for now? https://ci.md-5.net/job/BungeeCord/

We are using FlameCord for 1.7 support, there's a thing i tried to give the person the numerical ip address and he was able to connect but with the domain not

**Comment by jonesdevelopment** [comment]
> We are using FlameCord for 1.7 support, there's a thing i tried to give the person the numerical ip address and he was able to connect but with the domain not

Personally, I'd recommend just using Velocity (integrated 1.7.2-1.20.4 support) instead of BungeeCord. Not every plugin will work, but Velocity is a lot better than BungeeCord in terms of stability and performance. I know you probably cannot simply replace the jar file and run it like nothing has ever happened, but I strongly recommend at least giving it a try and looking into it.

**Comment by overkidding** [comment]
The update to velocity was planned but we're running custom plugins made for BungeeCord so we should first recode them ahhaha

**Comment by jonesdevelopment** [comment]
This will likely be fixed whenever https://github.com/jonesdevelopment/sonar/pull/174 is merged.

**Comment by jonesdevelopment** [comment]
Were you being disconnected (channel closed) or did you time out?
