### ISSUE TITLE
Feature Request: Spigot/Bukkit Support

### ISSUE THREAD

**Issue by micartey** [jonesdevelopment/sonar#179]
### Information

Sonar should support Spigot / Bukkit as well

### Reason

There are single server “networks”.
E.g., vanilla style survival servers.

**Comment by FallenCrystal** [comment]
i think this is duplicated of https://github.com/users/jonesdevelopment/projects/3?pane=issue&itemId=48685404

> if u just want to discuss something. u can join the discord (link in the README)

**Comment by micartey** [comment]
@FallenCrystal you are right. Didn't look at his board.
He should have created an issue from the Draft 🤔 

Well, now he has one 😆

**Comment by micartey** [comment]
@jonesdevelopment can you explain what you are currently struggling with?
I am sure I can find a solution. (Although I am more known for hacking the JVM than "best practices" as you know 😆 )

**Comment by ghost** [comment]
good suggestion

**Comment by StasM1X** [comment]
Up

**Comment by jonesdevelopment** [comment]
Sadly, working with Bukkit (NMS) is a lot harder than simply injecting into the BungeeCord/Velocity channel pipeline :/
Please allow me some more time on this. It's not my highest priority at the moment.

**Comment by MCPLAYER127272** [comment]
uP

**Comment by jonesdevelopment** [comment]
I understand that this is highly requested, but I don't have unlimited time.
You must understand that this requires a lot of work to be implemented.

**Comment by ghost** [comment]
> I understand that this is highly requested, but I don't have unlimited time. You must understand that this requires a lot of work to be implemented.

understood

**Comment by lolnikov** [comment]
+

**Comment by lolnikov** [comment]
+

**Comment by lolnikov** [comment]
Up

**Comment by lolnikov** [comment]
srpska

**Comment by jonesdevelopment** [comment]
@lolnikov Flooding my Emails with random characters will just get you ignored. I AM aware that people want this, and I AM planning to implement it for 2.1.0 or 2.0.19, but I DON'T have unlimited time. I am a human being (yes, I am), and I do go to university.

**Comment by rejomy** [comment]
Hello dear developer! Thank you very much for your hard work and updates, but please add this feature. I realize that you are a student and you probably have all the time to do personal stuff, but please, this is the best creation on the market and I would be madly happy if I could do it myself, but I can't. Please add it as soon as possible, I'll kiss your body if you do.

**Comment by jonesdevelopment** [comment]
> but please add this feature

Not sure when it'll be finished, but I'm hoping to be done within a couple of weeks.
Uhm, but you don't have to kiss my body for me to implement it :sweat_smile:

**Comment by GopnikDEV** [comment]
good waiting

**Comment by jonesdevelopment** [comment]
> good waiting

?

Bukkit support isn't easy to implement, and I currently lack the time to fully focus on it. I've started working on it, but you'll have to wait a bit. Contributions are welcome.

**Comment by StasM1X** [comment]
how going progress?

**Comment by jonesdevelopment** [comment]
> how going progress?

Not good. The base of Sonar is completely unstable on Bukkit. This isn't only about implementing some basic checks. Sonar's Fallback (name of the anti-bot component) is a complex project. You can take a look at it yourself:
https://github.com/jonesdevelopment/sonar/tree/main/sonar-common/src/main/java/xyz/jonesdev/sonar/common/fallback
I basically have to include support for every single version, fork, etc. without depending on mappings/special loaders.
One of the key problems is that I'll likely have to divide Sonar into multiple files: Bukkit/ Bungee & Velocity

**Comment by rejomy** [comment]
> **I need bukkit support for win my cat in discussion, my cat will suck, i am winner, my cat is so cute and beautiful, but she is very stupid... Please, dear developer, if you add bukkit support, i gift you my cat**

**Comment by jonesdevelopment** [comment]
Bukkit support will be implemented soon:
https://github.com/jonesdevelopment/sonar/pull/260 makes it possible to use Sonar on Bukkit, but there's no anti-bot yet.

**Comment by ghost** [comment]
nice to hear!!!

**Comment by Kowwwk** [comment]
3 анекдота с генератора анекдотов по просьбе Михаила F3F5
Хитрый малыш доплатил несущему его аисту 200 баксов и стал гражданином Швеции.
Обидно, когда два человека любят друг друга, но не могут быть вместе, потому что один из них дура.
В древней Спарте слабых и некрасивых мальчиков сбрасывали со скалы, а в наше время их отправляют по трое патрулировать станции метро.

**Comment by micartey** [comment]
@jonesdevelopment please delete the comment made by @Kowwwk

**Comment by ghost** [comment]
![bukkit](https://github.com/jonesdevelopment/sonar/assets/108226177/8fa04dd1-911e-4c04-95f2-479f3649f6b2)

**Comment by jonesdevelopment** [comment]
I know, you want Bukkit support... Sadly, I have final exams next week and the week after. I cannot do anything about that, so please allow me some more time to focus on my university work.

**Comment by F3F5** [comment]
you dont have life
