### ISSUE TITLE
Feature Request: Add console filter

### ISSUE THREAD

**Issue by Happies123** [jonesdevelopment/sonar#194]
### Information

Sonar is a good antibot but But he doesn't have any console filtering strategy I think you can add one now

### Reason

Sonar is a good antibot but But he doesn't have any console filtering strategy I think you can add one now
I tested your AntiBot using mcstorm and it was I9 13900k without much relief. The CPU utilization was above 40%, and after filtering the console, it was only 10% -20%

You can do a filter similar to BotSentry

For example:

Sonar AntiBot>Join: 34/s Motd: 230/s Ping: 230/s CPS: 2000 Queue: 23 Mode: AntiBot

In the console

### Additional information

I have translated your Soanr Antibot into Chinese. Do you need it? I can provide to everyone :)

**Comment by ghost** [comment]
![image](https://github.com/jonesdevelopment/sonar/assets/108226177/ded064a1-2f94-4b47-a1d3-48a356e0bfad)
Example

**Comment by Happies123** [comment]
yes

**Comment by jonesdevelopment** [comment]
Can you try turning off initial handler logging in `waterfall.yml`:
```yaml
log_initial_handler_connections: false
```

Then, please also try disabling ping logging in the BungeeCord `config.yml`:
```yaml
log_pings: false
```

**Comment by jonesdevelopment** [comment]
> I have translated your Soanr Antibot into Chinese. Do you need it? I can provide to everyone :)

Sure. I'm currently working on a language system so that would be really helpful.
Please join my Discord server and open a ticket to provide me the files. If you can't join my Discord server you can also post the messages here.

**Comment by jonesdevelopment** [comment]
@Happies123 Any news? Did my suggestion work for you?

**Comment by slosa** [comment]
> @Happies123 Any news? Did my suggestion work for you?

the only reasonable solution is to add booba verification

**Comment by jonesdevelopment** [comment]
Closed due to inactivity.
Check the #tutorials channel on Discord for more information regarding console filtering.
