### ISSUE TITLE
Bug Report: Impossible to connect in 1.20.5

### ISSUE THREAD

**Issue by NoltoxGit** [jonesdevelopment/sonar#279]
### General information

I've updated all my plugins on the Velocity side and when I try to connect in 1.20.5, it's impossible, but it works again when I deactivate the plugin.

### Steps to reproduce

1. Have the latest build of Velocity
2. Use the latest version of Sonar (2.0.27)
3. Try to connect in 1.20.5

### Sonar dump

[sonar]: Generated dump: {"memory":{"total":"188 MiB","max":"2.9 GiB","free":"45.5 MiB","used":"142.5 MiB"},"runtime":{"virtualCores":4,"jvmArguments":["-Xms128M","-Xmx2918M","-XX:+UseG1GC","-XX:G1HeapRegionSize\u003d4M","-XX:+UnlockExperimentalVMOptions","-XX:+ParallelRefProcEnabled","-XX:+AlwaysPreTouch","-XX:MaxInlineLevel\u003d15","-XX:+UnlockExperimentalVMOptions","-XX:+UnlockDiagnosticVMOptions","-XX:+AlwaysActAsServerClassMachine","-XX:+AlwaysPreTouch","-XX:+DisableExplicitGC","-XX:+UseNUMA","-XX:NmethodSweepActivity\u003d1","-XX:ReservedCodeCacheSize\u003d400M","-XX:NonNMethodCodeHeapSize\u003d12M","-XX:ProfiledCodeHeapSize\u003d194M","-XX:NonProfiledCodeHeapSize\u003d194M","-XX:-DontCompileHugeMethods","-XX:MaxNodeLimit\u003d240000","-XX:NodeLimitFudgeFactor\u003d8000","-XX:+UseVectorCmov","-XX:+PerfDisableSharedMem","-XX:+UseFastUnorderedTimeStamps","-XX:+UseCriticalJavaThreadPriority","-XX:AllocatePrefetchStyle\u003d3","-Dnet.kyori.ansi.colorLevel\u003dtruecolor"],"vmName":"OpenJDK 64-Bit Server VM","vmVendor":"Eclipse Adoptium","vmVersion":"21.0.2+13-LTS"},"os":{"name":"Linux","arch":"amd64","version":"6.1.0-0.deb11.11-amd64"},"sonar":{"version":"2.0.27-a17b726-1095-main","platform":"VELOCITY","isOnMainBranch":true}}

**Comment by jonesdevelopment** [comment]
Hello! 1.20.5 is not supported yet.
You can track the status here: https://github.com/jonesdevelopment/sonar/pull/278 — we're actively working on it.

**Comment by jonesdevelopment** [comment]
If you don't use the CAPTCHA (it doesn't work yet), you can try a custom build from @FallenCrystal's fork.
If you'd like me to provide you a version you can join the Discord server and open a ticket.

**Comment by NoltoxGit** [comment]
> If you don't use the CAPTCHA (it doesn't work yet), you can try a custom build from @FallenCrystal's fork. If you'd like me to provide you a version you can join the Discord server and open a ticket.

Okay, I'll join the Discord then, thanks a lot for the answer! :)

**Comment by jonesdevelopment** [comment]
#278
