### ISSUE TITLE
Bug Report: 2.0.29 use a lot of a RAM on start

### ISSUE THREAD

**Issue by NoltoxGit** [jonesdevelopment/sonar#292]
### General information

Hello,
I've just installed the latest version of Sonar on my Velocity server, and I've just noticed that as soon as the server has finished booting, it crashes for an “out of memory”.

On my Velocity, I've allocated it 1GB of RAM (more than enough) as it consumes an average of 600MB of RAM.

But with the latest version, Sonar jumps several hundred MB and crashes the server.

The previous version (2.0.28) does not have this problem.

Also, I can't give the dump of the latest version.

### Steps to reproduce

1. Update to the latest version of Sonar

### Sonar dump

sonar]: Generated dump: {"memory":{"total":"180 MiB","max":"976 MiB","free":"24.4 MiB","used":"155.6 MiB"},"runtime":{"virtualCores":4,"jvmArguments":["-Xms128M","-Xmx975M","-XX:+UseG1GC","-XX:G1HeapRegionSize\u003d4M","-XX:+UnlockExperimentalVMOptions","-XX:+ParallelRefProcEnabled","-XX:+AlwaysPreTouch","-XX:MaxInlineLevel\u003d15","-XX:+UnlockExperimentalVMOptions","-XX:+UnlockDiagnosticVMOptions","-XX:+AlwaysActAsServerClassMachine","-XX:+AlwaysPreTouch","-XX:+DisableExplicitGC","-XX:+UseNUMA","-XX:NmethodSweepActivity\u003d1","-XX:ReservedCodeCacheSize\u003d400M","-XX:NonNMethodCodeHeapSize\u003d12M","-XX:ProfiledCodeHeapSize\u003d194M","-XX:NonProfiledCodeHeapSize\u003d194M","-XX:-DontCompileHugeMethods","-XX:MaxNodeLimit\u003d240000","-XX:NodeLimitFudgeFactor\u003d8000","-XX:+UseVectorCmov","-XX:+PerfDisableSharedMem","-XX:+UseFastUnorderedTimeStamps","-XX:+UseCriticalJavaThreadPriority","-XX:AllocatePrefetchStyle\u003d3","-Dnet.kyori.ansi.colorLevel\u003dtruecolor"],"vmName":"OpenJDK 64-Bit Server VM","vmVendor":"Eclipse Adoptium","vmVersion":"21.0.3+9-LTS"},"os":{"name":"Linux","arch":"amd64","version":"6.1.0-13-amd64"},"sonar":{"version":"2.0.28-595b137-1099-main","platform":"VELOCITY","isOnMainBranch":true}}

**Comment by jonesdevelopment** [comment]
Do you have a spark report for me to look at?
I'm using 64MB for my proxy and I never ran into this issue...

**Comment by NoltoxGit** [comment]
> Do you have a spark report for me to look at? I'm using 64MB for my proxy and I never ran into this issue...

Yes I've spark, there is a profiler: https://spark.lucko.me/HvWSe9uaW8

**Comment by jonesdevelopment** [comment]
Are you using the new CAPTCHA?

**Comment by jonesdevelopment** [comment]
![image](https://github.com/jonesdevelopment/sonar/assets/73846784/7e2326b0-fd65-42ba-aadb-e3ca96958bdb)

This shows Sonar 2.0.28, and it's not consuming anything. Are you sure this is the correct spark report?

**Comment by jonesdevelopment** [comment]
@NoltoxGit Can you open a ticket on Discord? It's easier to communicate there. https://jonesdev.xyz/discord

**Comment by andreasdc** [comment]
I think a memory dump will be better.

**Comment by jonesdevelopment** [comment]
Fixed it. I was accidentally preparing packets containing a huge amount of data :)
