### ISSUE TITLE
Bug Report: TCPShield compatibility

### ISSUE THREAD

**Issue by FabrisNick** [jonesdevelopment/sonar#299]
### General information

Sonar is not compatible with TCPShield.
Sonar doesn't get the real IPs

### Steps to reproduce

1. Configure TCPShield proxy
2. Install latest sonar and TCPShield plugin
3. Join the server

### Sonar dump

[sonar]: Generated dump: {"memory":{"total":"1 GiB","max":"1 GiB","free":"900 MiB","used":"124 MiB"},"runtime":{"virtualCores":4,"jvmArguments":["-Xms1G","-Xmx1G","-XX:+UseG1GC","-XX:G1HeapRegionSize\u003d4M","-XX:+UnlockExperimentalVMOptions","-XX:+ParallelRefProcEnabled","-XX:+AlwaysPreTouch","-XX:MaxInlineLevel\u003d15"],"vmName":"OpenJDK 64-Bit Server VM","vmVendor":"Eclipse Adoptium","vmVersion":"21.0.3+9-LTS"},"os":{"name":"Linux","arch":"amd64","version":"6.5.0-1019-azure"},"sonar":{"version":"2.0.30-a7d5246-1110-main","platform":"VELOCITY","isOnMainBranch":true}}

**Comment by UTrosh** [comment]
send your config

**Comment by FallenCrystal** [comment]
The TCPShield plugin is not currently supported. Please check this [document](https://docs.tcpshield.com/commonly-asked-questions#1.-differences-between-our-plugin-vs-proxy-protocol)

**Comment by jonesdevelopment** [comment]
TCPShield themselves state that you shouldn't use the plugin anymore. Although Sonar **should theoretically** be compatible with the plugin (maybe it's only working on BungeeCord?)...
Read more here: https://discord.com/channels/923308209769426994/1211287926055370792
