### ISSUE TITLE
Feature Request: Remove /sonar notify

### ISSUE THREAD

**Issue by jonesdevelopment** [jonesdevelopment/sonar#301]
### Information

Would you be okay with me removing this feature or not?
I'll keep this issue open for some time so you can discuss it in the comments.

### Reason

Not only is /sonar notify (not /sonar verbose!) rarely used, but it also takes up some code. I'd like to minimize Sonar's codebase.

**Comment by jonesdevelopment** [comment]
To clarify again: this is about `/sonar notify`, not `/sonar verbose`. These commands do different things.

**Comment by Dynamic-Gravity** [comment]
Personally, I do not find it useful to alert in a discord channel. I use Uptime Kuma to monitor my services, and it can be configured with just a webhook, to alert me via PagerDuty.

I see the user story for wanting to have this feature so I don't think it would be the right call to remove it. If you're concerned with bundle size maybe to preserve the functionality move it to to a separate extras package or something?

**Comment by jonesdevelopment** [comment]
> Personally, I do not find it useful to alert in a discord channel

`/sonar notify` **only** covers the in-game chat and title notifications when an attack is detected.

**Comment by jonesdevelopment** [comment]
> If you're concerned with bundle size maybe to preserve the functionality move it to to a separate extras package or something?

I wanted to either recode it or remove it entirely since the current implementation just... *works*.

**Comment by jonesdevelopment** [comment]
It doesn't seem like people want this, so I'm going to close this issue.
Discord poll: https://discord.com/channels/923308209769426994/947920255211163688/1240360286666362890
