### ISSUE TITLE
Bug Report: Invalid timestamp in MySQL database

### ISSUE THREAD

**Issue by bilemedimkq** [jonesdevelopment/sonar#331]
### General information

![image](https://github.com/jonesdevelopment/sonar/assets/42588052/57d45197-c34a-484f-b69a-c578760bb1af)
The timestamp in the MySQL database is not correct. 
I changed manually first line.

because of that, when I rebooted the server all the players checking again.

### Steps to reproduce

run the plugin any belocity server

### Sonar dump

[sonar]: Generated dump: {"memory":{"total":"136 MiB","max":"14.8 GiB","free":"86.9 MiB","used":"49.1 MiB"},"runtime":{"virtualCores":6,"jvmArguments":["-Xms128M","-XX:MaxRAMPercentage\u003d95.0"],"vmName":"OpenJDK 64-Bit Server VM","vmVendor":"Eclipse Adoptium","vmVersion":"21.0.3+9-LTS"},"os":{"name":"Linux","arch":"amd64","version":"5.15.0-107-generic"},"sonar":{"version":"2.0.32-15af0f3-1131-main","platform":"VELOCITY","isOnMainBranch":true}}

**Comment by bilemedimkq** [comment]
the server is working in a docker container, the time in the docker is correct. I checked.

**Comment by jonesdevelopment** [comment]
Can confirm. I'm accidentally using the time taken (in milliseconds), and not the timestamp.

**Comment by jonesdevelopment** [comment]
I'll push a fix ASAP. Affected files:
<https://github.com/jonesdevelopment/sonar/blob/main/sonar-common/src/main/java/xyz/jonesdev/sonar/common/fallback/session/FallbackSessionHandler.java#L62-L63>

**Comment by bilemedimkq** [comment]
I am going to add some information but you're already fix that :D 

dude, that was so fast

**Comment by jonesdevelopment** [comment]
You can get the fixed version by either manually compiling Sonar or joining the [Discord](https://jonesdev.xyz/discord) and opening a ticket (I'll send you a version with the fix).

**Comment by bilemedimkq** [comment]
do you have cicd or I need to build plugin myself ?
