### ISSUE TITLE
Bug Report: Player 1.21 fails to connect due to sonar plugin

### ISSUE THREAD

**Issue by LOURENT4462** [jonesdevelopment/sonar#334]
### General information

Previously, I could say this problem came from sonar because when I deactivated the plugin... this problem did not appear and players could join normally

I tested with velocity build #399 and client with minecraft (using minecraft launcher) with version 1.21 (without optifine and any additions)

![image](https://github.com/jonesdevelopment/sonar/assets/99059205/587c7af0-b96f-4c22-b6ac-6ccbbcbc2d14)
so when the player logs in to the server, a message appears like in the picture I attached

console log (from velocity proxy)
`[18:15:18] [Netty epoll Worker #0/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [initial connection] /xxx.xxx.xxx.xxx:xxxxx has disconnected`

and the problem doesn't exist when I disable sonar (as I explained above)

### Steps to reproduce

1. Join the velocity proxy (client: minecraft 1.21) (with the sonar plugin installed)
2. player disconnected with message `failed to connect to the server - disconnected`

### Sonar dump

>....[18:33:25 INFO] [sonar]: Generated dump: {"memory":{"total":"512 MiB","max":"1.5 GiB","free":"352.3 MiB","used":"159.7 MiB"},"runtime":{"virtualCores":2,"jvmArguments":["-Xms512M","-Xmx1500M","-XX:MaxRAMPercentage\u003d95.0"],"vmName":"OpenJDK 64-Bit Server VM","vmVendor":"Eclipse Adoptium","vmVersion":"17.0.11+9"},"os":{"name":"Linux","arch":"amd64","version":"4.18.0-477.27.1.el8_8.x86_64"},"sonar":{"version":"2.0.32-15af0f3-1131-main","platform":"VELOCITY","isOnMainBranch":true}}

### Additional information

-

**Comment by jonesdevelopment** [comment]
Sonar's latest release (2.0.32) doesn't support 1.21 yet.

Discord announcement: https://discord.com/channels/923308209769426994/947920255211163688/1251869288315486283

If you need a development build, please open a ticket on the [Discord server](<https://jonesdev.xyz/discord>).

**Comment by jonesdevelopment** [comment]
(1.21 support was already implemented in https://github.com/jonesdevelopment/sonar/pull/322, but it's not available for public download yet. There aren't even any Paper releases out yet, so you shouldn't be running 1.21 in the first place)
