### ISSUE TITLE
Feature Request: Particle Effect CAPTCHA

### ISSUE THREAD

**Issue by TianmuTNT** [jonesdevelopment/sonar#338]
### Information

![2024-06-08_00 32 26](https://github.com/jonesdevelopment/sonar/assets/110798004/e1211c01-ee29-4f2c-9d62-316374bf6068)
I would like to propose the addition of a new feature to the anti-bot plugin: a particle effect-based CAPTCHA. This feature aims to enhance server security by reducing bot bypasses and simplifying the player joining process.
This feature is not directly related to any existing issues or errors.
However, it addresses the need for improved anti-bot measures.

### Reason

Particle effect CAPTCHAs are almost impossible for bots to bypass.
Traditional image-based CAPTCHAs can be cumbersome for players, especially those who struggle with reading complex images.

### Additional information

My English is not very good, and I am using translation software. If there is any confusion in my message, I apologize.

**Comment by jonesdevelopment** [comment]
Hi, I've seen this before, and decided not to implement something like this.

Reasons:
- Sending 500-800 particles every 0.5 seconds is not good for traffic
- Most people have particles on "Decreased" or "Minimized", therefore making this useless

**Comment by TianmuTNT** [comment]
Hi,

Could we add an option in the configuration file to enable or disable the particle effect captcha? Additionally, we could include an option to adjust the size of the particles forming the text. This way, we address both concerns you mentioned.

**Comment by jonesdevelopment** [comment]
> Could we add an option in the configuration file to enable or disable the particle effect captcha

Sorry, but "just make it configurable" isn't going to resolve the problem. It's just more work for me to do. I don't think it's worth it.

> include an option to adjust the size of the particles forming the text

I would still need to have a timer task running in the background that sends all particles. Making the particles resizable makes it just more complicated to implement this feature.

Additionally, people are given the option to disable particles in the vanilla Minecraft client. With maps, people will always see what we display. No mod will change the inbound packets to display a different map. With particles, people can just turn them off, and many people actually do. There are mods designed to remove particles, as they are usually bad for client performance.

I think using particles is even worse than a traditional map CAPTCHA. Attackers would need to collect the X and Y positions of the particles and then they can use AI to get the text from the coordinate system of all points. This doesn't even require an advanced image recognition AI, as there are no effects applied on the text.

![image](https://github.com/jonesdevelopment/sonar/assets/73846784/83edc146-6250-4251-961a-fc3169451c27)

The use of different colors makes it actually easier to decipher the code.

**Comment by TianmuTNT** [comment]
No worries! Thank you for developing such a useful plugin and taking the time to explain it to someone like me.

**Comment by F3F5** [comment]
looks interesting
