### ISSUE TITLE
Feature Request: Add support for local databases

### ISSUE THREAD

**Issue by jonesdevelopment** [jonesdevelopment/sonar#341]
### Information

Add support for local databases (e.g. H2) using ORMLite

### Reason

> I'm only missing a local database. Not everyone uses MySQL or MariaDB, so support for H2, SQLite or JSON would be necessary in this plugin.

https://www.spigotmc.org/resources/sonar.115239/reviews#review-547425-612130

**Comment by F3F5** [comment]
@HaHaWTH
