### ISSUE TITLE
Feature Request: Use shared exceptions in hot code

### ISSUE THREAD

**Issue by ghost** [jonesdevelopment/sonar#372]
### Information

Java exception are usually [pretty heavy](https://shipilev.net/blog/2014/exceptional-performance/)[^1] to construct. Unfortunately, they are used in lots of hot code, [here](https://github.com/jonesdevelopment/sonar/blob/ef6140d47f1666d054e6b3ef95228b52ae7b8bd3/sonar-common/src/main/java/xyz/jonesdev/sonar/common/fallback/FallbackUserWrapper.java#L189), [here](https://github.com/jonesdevelopment/sonar/blob/ef6140d47f1666d054e6b3ef95228b52ae7b8bd3/sonar-common/src/main/java/xyz/jonesdev/sonar/common/fallback/protocol/FallbackPacketDecoder.java#L104-L111), [here](https://github.com/jonesdevelopment/sonar/blob/ef6140d47f1666d054e6b3ef95228b52ae7b8bd3/sonar-common/src/main/java/xyz/jonesdev/sonar/common/fallback/netty/FallbackVarInt21FrameDecoder.java#L73), and in many other places, where bots can quickly connect and disconnect, filling the stack traces, that will not be used anywhere. My proposal is to use shared constant (`static final`) stackless exceptions, where message is static, like [here](https://github.com/jonesdevelopment/sonar/blob/ef6140d47f1666d054e6b3ef95228b52ae7b8bd3/sonar-common/src/main/java/xyz/jonesdev/sonar/common/fallback/protocol/FallbackPacketDecoder.java#L105) or [here](https://github.com/jonesdevelopment/sonar/blob/ef6140d47f1666d054e6b3ef95228b52ae7b8bd3/sonar-common/src/main/java/xyz/jonesdev/sonar/common/fallback/session/FallbackCAPTCHASessionHandler.java#L54) AND plain, dynamically-constructed, stackless exceptions where exception message is dynamic, if these exist[^2].

[^1]: This post is from 2014, now exceptions are a little bit more performant.
[^2]: I couldn't find a single one.

### Reason

Performance.

### Additional information

See Velocity's [implemetation](https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/util/except/QuietDecoderException.java), [preconditions](https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/protocol/util/NettyPreconditions.java), and [usage](https://github.com/PaperMC/Velocity/blob/6100e675af9d85358403cf84893a6bdaddd2d519/proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java#L263). Additionally, I believe, that the synchronized block can be removed too, as it's a no-op. Many methods can be overridden, such as `getStackTrace()` to return a constant shared array, but I don't believe they will provide a big perfomance boost.

I do understand that after an exception, the client is immediately disconnected. While you can't usually override and replace Netty exceptions, such as OOB exceptions, this approah may give some protection at the Sonar level.

**Comment by jonesdevelopment** [comment]
Very interesting; thanks for pointing this out. I'll definitely fix this in future commits.

**Comment by jonesdevelopment** [comment]
@whiler-sesame Feel free to check out my PR https://github.com/jonesdevelopment/sonar/pull/373 if you're interested.
