### ISSUE TITLE
ProtocolSupport compatibility (legacy)

### ISSUE THREAD

**Issue by calors22** [jonesdevelopment/sonar#388]
.

**Comment by jonesdevelopment** [comment]
Hello,

Travertine is 4 years old (2020-11-02). Sonar is supposed to support BungeeCord 1.21 and above. I am not going to bother implementing and maintaining/providing support for software that is this outdated. If you need 1.7 support, use Velocity.

Additionally, ViaVersion and ProtocolSupport are not supposed to be put on the proxy. BungeeCord has built-in 1.8-1.21.1 support, and Velocity supports 1.7.2-1.21.1. You only need these kinds of plugins on the backend servers where Sonar isn't going to cause issues in the first place.

> to be additional configuration that supports

As always, "make it configurable" is not an option.

Link to Velocity: https://papermc.io/downloads/velocity
You can find more information regarding this matter on the Discord server: https://jonesdev.xyz/discord
