### ISSUE TITLE
slot out of range

### ISSUE THREAD

**Issue by katze225** [jonesdevelopment/sonar#395]
### General information

Иногда некоторых игроков считает за бота по причине "slot out of range"

### Steps to reproduce

Проблема появляется случайно, в некоторых игроков. Примерно каждый 20-30 игрок с таким сталкиваеться 

### Sonar dump

[sonar]: Generated dump: {"memory":{"total":"2 GiB","max":"2.1 GiB","free":"1.4 GiB","used":"630.4 MiB"},"runtime":{"virtualCores":2,"jvmArguments":["-Xms128M","-XX:MaxRAMPercentage\u003d95.0","-XX:+UseG1GC","-XX:G1HeapRegionSize\u003d4M","-XX:+UnlockExperimentalVMOptions","-XX:+ParallelRefProcEnabled","-XX:+AlwaysPreTouch","-XX:MaxInlineLevel\u003d15"],"vmName":"OpenJDK 64-Bit Server VM","vmVendor":"Eclipse Adoptium","vmVersion":"21.0.3+9-LTS"},"os":{"name":"Linux","arch":"amd64","version":"5.15.0-122-generic"},"sonar":{"version":"2.1.10 (3c73ecf6)","platform":"VELOCITY","gitBranch":"main","gitCommit":"3c73ecf6"}}

**Comment by jonesdevelopment** [comment]
Make sure these players are logging in with a vanilla client. This is not vanilla behaviour and cannot be fixed. Anti-cheat plugins would instant-ban for this.
