### ISSUE TITLE
Command rate liniter on proxy servers

### ISSUE THREAD

**Issue by pepters** [jonesdevelopment/sonar#416]
### Information

Add an option to rate limit only proxy or all proxy to limit potential attackers from spamming

### Reason

We have no rate limit plugins on velocity

### Additional information

I know that this does not apply to the anti-bot plugin, but I would really like to see it

**Comment by pepters** [comment]
I mean command rate-limit

**Comment by jonesdevelopment** [comment]
This is out-of-scope for Sonar, especially considering that it has nothing to do with the tasks of an anti-bot plugin in the first place.

New feature requests for Sonar 2.0 will be closed, as 3.0 is in the making. You can find more information on the Discord server: https://jonesdev.xyz/discord
