### ISSUE TITLE
Bug Report: THANKS SONAR FOR BANNING ME FROM SERVERS I DONT WANT INSTALL VERSIONS I NEED TO USE VIAFABRIC TO JOIN TO SHIT SERVERS

### ISSUE THREAD

**Issue by sprytex** [jonesdevelopment/sonar#424]
### General information

Bug Report: THANKS SONAR FOR BANNING ME FROM SERVERS I DONT WANT INSTALL VERSIONS I NEED TO USE VIAFABRIC TO JOIN TO SHIT SERVERS

### Steps to reproduce

Bug Report: THANKS SONAR FOR BANNING ME FROM SERVERS I DONT WANT INSTALL VERSIONS I NEED TO USE VIAFABRIC TO JOIN TO SHIT SERVERS

### Sonar dump

Bug Report: THANKS SONAR FOR BANNING ME FROM SERVERS I DONT WANT INSTALL VERSIONS I NEED TO USE VIAFABRIC TO JOIN TO SHIT SERVERS

### Additional information

Bug Report: THANKS SONAR FOR BANNING ME FROM SERVERS I DONT WANT INSTALL VERSIONS I NEED TO USE VIAFABRIC TO JOIN TO SHIT SERVERS

**Comment by sprytex** [comment]
antibot banned servers for me because this shit is popularity and i dont wanna install 2490240924 versions to join. 1 star ALWAYS!

**Comment by jonesdevelopment** [comment]
Don't you have something better to do?
