### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by r7mc** [jonesdevelopment/sonar#425]
### Information

When using with LimboAuth, is it possible to add an option to not kick out the server after verification, but to perform login verification instead?

### Reason

transfer.enabled = true, and cannot redirect to local server

**Comment by jonesdevelopment** [comment]
> transfer.enabled = true, and cannot redirect to local server

Make sure to set up transferring correctly: https://www.youtube.com/watch?v=aSWrzQVjGnc

**Comment by jonesdevelopment** [comment]
It would be helpful if you could provide the problematic configuration lines you mentioned.
