### ISSUE TITLE
Feature Request: Change stone block in fall check to barrier

### ISSUE THREAD

**Issue by arm4xlll** [jonesdevelopment/sonar#52]
### Information

you can replace the blocks that players fall on during checks to invisible(barriers)? visually it will look clean

### Reason

aesthetics

### Additional information

-

**Comment by jonesdevelopment** [comment]
Nice idea, but it's a pain for me to check the block ids for each version which is why I've been stuck with stone blocks for now. Block ids, especially on 1.13+, are a mess.
I'll add it to my to-do list but I cannot say when this will be implemented.

**Comment by jonesdevelopment** [comment]
I'll recode the gravity check first and then I'll look into the block id stuff.

If you want to receive update notifications, you can join [my Discord server](https://jonesdev.xyz/discord) if you are interested.

**Comment by jonesdevelopment** [comment]
Update: barriers seem to work on 1.8-1.12.2, but not on 1.13+ because of the flattening update which changed the block id behaviour. I also had to replace them with glass blocks on 1.7 since 1.7 doesn't have barrier blocks.
I'll keep trying to find out a way to map the block ids!

**Comment by jonesdevelopment** [comment]
Found a solution for the missing state ids! I will open a PR soon.
