### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by UTrosh** [jonesdevelopment/sonar#6]
### General information

With JPremium V1.17 and latest sonar, jpremium cant handle unique id / join event i think,
here is the error :
[16:00:41] [Netty Worker IO Thread #2/WARN]: Error dispatching event LoginEvent(cancelled=false, cancelReasonComponents=null, loginResult=LoginResult(id=da1200b376bf48348a30bd32b970acd9, name=wUTrosh, properties=[Property(name=textures, value=e***=)]), connection=(/90.93.27.109:52427|wUTrosh) <-> InitialHandler) to listener com.jakub.premium.c.c@25b5a989
java.lang.NoSuchFieldException: uniqueId

### Java version

Java 17

### Server type

Waterfall

### Server version

Latest waterfall

**Comment by jonesdevelopment** [comment]
I will look into it ASAP

**Comment by FallenCrystal** [comment]
> Sonar doesn't have the `uniqueId` field. It supports `getUniqueId()` in the InitialHandler. I really don't have the time to completely copy and redo all of the stuff inside of the original InitialHandler. You can contact the developers and tell them to use the getter instead of the field using Reflections.

jpremium uses reflection to modify a player's uuid. this can break through the situation where the bungeecord cannot modify the online player's uuid.
thanks for creating such a great antibot plugin. If there is time. i'll try to figure this out and add compatibility.

**Comment by FallenCrystal** [comment]
@UTrosh u can try this jar? [Sonar.zip](https://github.com/jonesdevelopment/sonar/files/11859080/Sonar.zip)

**Comment by UTrosh** [comment]
I'll try it

**Comment by jonesdevelopment** [comment]
Should be fixed in #8 
Tested with BotFilter (BungeeCord)
