### ISSUE TITLE
Feature Request: 1.20.2 support

### ISSUE THREAD

**Issue by jonesdevelopment** [jonesdevelopment/sonar#61]
### Information

Announcement: https://forums.papermc.io/threads/paper-velocity-1-20-2.920/

### Reason

Provide support for Minecraft version 1.20.2 as Velocity and Paper for 1.20.2 have been released.

### Additional information

https://github.com/PaperMC/Velocity/commit/768ecdb0c36dd20779b8a9733ade42a60bf7c3c6

**Comment by jonesdevelopment** [comment]
Velocity versions b266+ are currently unsupported — Version 2.0.4 will fully support b265 and all versions above.
https://discord.com/channels/923308209769426994/947920255211163688/1162140227989688391

**Comment by jonesdevelopment** [comment]
Waiting for https://github.com/PrismarineJS/minecraft-data to publish 1.20.2 mappings

**Comment by jonesdevelopment** [comment]
Check https://github.com/jonesdevelopment/sonar/pull/65 for more information

**Comment by jonesdevelopment** [comment]
https://github.com/PrismarineJS/minecraft-data/issues/779

**Comment by jonesdevelopment** [comment]
https://github.com/PrismarineJS/minecraft-data/pull/786

**Comment by Dynamic-Gravity** [comment]
So support for this version, 1.20.2, is currently blocked by the linked issues? Thank you for posting with this info.

**Comment by jonesdevelopment** [comment]
> So support for this version, 1.20.2, is currently blocked by the linked issues? Thank you for posting with this info.

https://github.com/PrismarineJS/minecraft-data/pull/786 has been merged, so the block state id isn't the issue anymore.
I'm currently recoding the JoinGame and ChunkData packet to work on 1.20.2+.

1.20.2 itself is supported, but the checks aren't advanced yet since I cannot check for gravity/collisions without the ChunkData packet.

**Comment by Dynamic-Gravity** [comment]
> 1.20.2 itself is supported, but the checks aren't advanced yet since I cannot check for gravity/collisions without the ChunkData packet.

The reason I asked was because I have a Waterfall-1.20 (build 551) and Purpur-1.20.2-build-2088 and when I go to connect I get a null pointer exception with the `net.md_5.bungee.netty.HandlerBoss:111` class . I had thought this would be related to this issue.

If you could provide any feedback on why I am experiencing this issue I would greatly appreciate it, thank you :)

**Comment by jonesdevelopment** [comment]
> The reason I asked was because I have a Waterfall-1.20 (build 551) and Purpur-1.20.2-build-2088 and when I go to connect I get a null pointer exception with the `net.md_5.bungee.netty.HandlerBoss:111` class . I had thought this would be related to this issue.

I did not know about this issue. Could you provide the full stacktrace (error log)? You can also open a ticket on the Discord server if you want to directly contact me.
