### ISSUE TITLE
Bug Report: "Root tag must be a named compound tag" on join

### ISSUE THREAD

**Issue by TheDeafCreeper** [jonesdevelopment/sonar#68]
### General information

When attempting to join a Velocity Proxy (b276, also  tried b264) with Sonar installed, I get immediately kicked with the error in the title.
(Full error in case it matters)
```
Internal Exception: io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.IOException: Root tag must be a named compound tag
```

The error occurs on:
- Vanilla 1.19.4
- Vanilla 1.20.1
- Modded 1.20.1

I successfully joined using Vanilla 1.20.2

I believe that the error is a client side error, but it happening in vanilla, as well as only when using Sonar seems to indicate Sonar is causing it.

### Steps to reproduce

1. Install Sonar (I tried on Velocity)
2. Join Proxy/Server

### Sonar dump

{"memory":{"total":"560.0 MB","max":"15.7 GB","free":"409.7 MB","used":"150.3 MB"},"runtime":{"virtualCores":16,"jvmArguments":[],"vmName":"OpenJDK 64-Bit Server VM","vmVendor":"Oracle Corporation","vmVersion":"21+35"},"os":{"name":"Linux","arch":"amd64","version":"6.1.57-1-lts"},"sonar":{"version":"2.0.4-1671cca-928-main","platform":"VELOCITY","isOnMainBranch":true}}

**Comment by jonesdevelopment** [comment]
I can confirm this issue; thank you for reporting this. For now, please try version 2.0.3 on Velocity b265 or below.

**Comment by jonesdevelopment** [comment]
Should be fixed in https://github.com/jonesdevelopment/sonar/commit/a4b6d49bf66421386a9d2eca10a058afc771108d. Will test with 1.19.4, 1.20, 1.20.1 and 1.20.2

**Comment by jonesdevelopment** [comment]
I broke it again. This will be fixed in Sonar 2.0.5

**Comment by jonesdevelopment** [comment]
@TheDeafCreeper 2.0.5 has been released.

**Comment by TheDeafCreeper** [comment]
Saw it,  thanks!
